server:
  port: 8089
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.92.126.206:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
#    host: 182.92.126.206
    host: 127.0.0.1
    port: 6379
#    password: 123456
    database: 0

#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
markerhub:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNjM1NjQ2MTY5LCJleHAiOjE2NDE2OTQxNjl9.2Qor-f2CJqXUt669f04ac3jFlk_yd6CVmwl9XHW9strE3AUvxxf9NeCikf3NBDvrsUf1n1wKDwDzOG6tzVXpJA